apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
      tier: backend
  template:
    metadata:
      labels:
        app: posts
        tier: backend
    spec:
      containers:
        - name: posts
          image: mrwin95/posts:v1          